import React, { createContext, useState, useEffect, useContext } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

const SettingsContext = createContext();

const translations = {
    English: {
        dashboard: "Dashboard",
        expense: "Expenses",
        report: "Report",
        profile: "Profile",
        builder_details: "Builder Details",
        app_settings: "App Settings",
        logout: "Logout",
        save_changes: "Save Changes",
        home: "Home",
        account_settings: "Account Settings",
        app_preferences: "App Preferences",
        personal_info: "Personal Info",
        confirm_apply: "Confirm & Apply",
        hero_title: "Your\nFinancial\nNavigator",
        hero_subtitle: "Invest in projects that make a difference. Join us in supporting impactful initiatives and create a positive change in the world.",
        get_started: "Get Started",
        security: "Security",
        security_sublabel: "Password and authentication",
        builder_details_sublabel: "Business details, GST, PAN, and address",
        app_settings_sublabel: "Currency, Language, Theme, & More",
        expense_overview: "Expense Overview",
        total_expenses: "Total Expenses",
        no_expenses: "No expenses yet. Tap + to add one.",
        add_expense_title: "Add Expense",
        vendor_name: "Vendor Name",
        material_category: "Material Category",
        quantity: "Quantity",
        unit: "Unit",
        rate_per_unit: "Rate per Unit",
        total_amount_label: "Total Amount",
        payment_mode: "Payment Mode",
        project_tag: "Project Tag",
        notes: "Notes",
        add_expense_btn: "Add Expense",
        cancel: "Cancel",
        search_placeholder: "Search vendor or date...",
        localization: "Localization",
        default_currency: "Default Currency",
        app_language: "App Language",
        formatting_defaults: "Formatting & Defaults",
        date_format: "Date Format",
        default_payment: "Default Payment Mode",
        appearance: "Appearance",
        theme_mode: "Theme Mode",
        current: "Current",
        pref_updated: "Preferences updated and applied globally!",
        success: "Success",
        error: "Error",
        fail_save: "Failed to save preferences.",
        select_date: "Select Date",
        delete: "Delete",
        confirm_apply_info: "Confirming changes will apply them instantly across the entire application.",
        financial_future: "Take control of your financial future.",
        data_management: "Data Management",
        data_management_sublabel: "Backup, export, and secure storage",
        last_backup: "Last Backup",
        backup_now: "Backup Now",
        auto_backup: "Auto Backup Frequency",
        export_data: "Export All Data",
        import_data: "Import from Excel",
        storage_usage: "Storage Usage",
        danger_zone: "Danger Zone",
        clear_all_data: "Clear All Data",
        confirm_clear_title: "Are you sure?",
        confirm_clear_msg: "This will permanently delete all your expense records. This action cannot be undone.",
        password_confirm: "Enter password to confirm",
        back_up_success: "Backup synced successfully",
        clear_success: "Data cleared successfully",
        backup_none: "Never",
        daily: "Daily",
        weekly: "Weekly",
        monthly: "Monthly",
        none: "None",
    },
    Hindi: {
        dashboard: "डैशबोर्ड",
        expense: "खर्च",
        report: "रिपोर्ट",
        profile: "प्रोफ़ाइल",
        builder_details: "बिल्डर विवरण",
        app_settings: "ऐप सेटिंग्स",
        logout: "लॉगआउट",
        save_changes: "परिवर्तन सहेजें",
        home: "होम",
        account_settings: "खाता सेटिंग्स",
        app_preferences: "ऐप प्राथमिकताएं",
        personal_info: "व्यक्तिगत जानकारी",
        confirm_apply: "पुष्टि करें और लागू करें",
        hero_title: "आपका\nवित्तीय\nसलाहकार",
        hero_subtitle: "उन परियोजनाओं में निवेश करें जो बदलाव लाती हैं। प्रभावशाली पहलों का समर्थन करने और दुनिया में सकारात्मक बदलाव लाने में हमारे साथ जुड़ें।",
        get_started: "शुरू करें",
        security: "सुरक्षा",
        security_sublabel: "पासवर्ड और प्रमाणीकरण",
        builder_details_sublabel: "व्यवसाय विवरण, जीएसटी, पैन और पता",
        app_settings_sublabel: "मुद्रा, भाषा, थीम और अधिक",
        expense_overview: "खर्च अवलोकन",
        total_expenses: "कुल खर्च",
        no_expenses: "अभी तक कोई खर्च नहीं। जोड़ने के लिए + टैप करें।",
        add_expense_title: "खर्च जोड़ें",
        vendor_name: "विक्रेता का नाम",
        material_category: "सामग्री श्रेणी",
        quantity: "मात्रा",
        unit: "इकाई",
        rate_per_unit: "प्रति इकाई दर",
        total_amount_label: "कुल राशि",
        payment_mode: "भुगतान विधि",
        project_tag: "परियोजना टैग",
        notes: "नोट्स",
        add_expense_btn: "खर्च जोड़ें",
        cancel: "रद्द करें",
        search_placeholder: "विक्रेता या तिथि खोजें...",
        localization: "स्थानीयकरण",
        default_currency: "डिफ़ॉल्ट मुद्रा",
        app_language: "ऐप भाषा",
        formatting_defaults: "फॉर्मेटिंग और डिफ़ॉल्ट",
        date_format: "तिथि प्रारूप",
        default_payment: "डिफ़ॉल्ट भुगतान विधि",
        appearance: "दिखावट",
        theme_mode: "थीम मोड",
        current: "वर्तमान",
        pref_updated: "प्राथमिकताएं अपडेट की गईं और विश्व स्तर पर लागू की गईं!",
        success: "सफलता",
        error: "त्रुटि",
        fail_save: "प्राथमिकताएं सहेजने में विफल।",
        select_date: "तिथि चुनें",
        delete: "हटाएं",
        confirm_apply_info: "परिवर्तनों की पुष्टि करने से वे पूरे आवेदन में तुरंत लागू हो जाएंगे।",
        financial_future: "अपने वित्तीय भविष्य पर नियंत्रण रखें।",
        data_management: "डेटा प्रबंधन",
        data_management_sublabel: "बैकअप, निर्यात और सुरक्षित संग्रहण",
        last_backup: "पिछला बैकअप",
        backup_now: "अभी बैकअप लें",
        auto_backup: "ऑटो बैकअप आवृत्ति",
        export_data: "सभी डेटा निर्यात करें",
        import_data: "एक्सेल से आयात करें",
        storage_usage: "भंडारण उपयोग",
        danger_zone: "खतरनाक क्षेत्र",
        clear_all_data: "सभी डेटा साफ़ करें",
        confirm_clear_title: "क्या आप निश्चित हैं?",
        confirm_clear_msg: "यह आपके सभी खर्च रिकॉर्ड को स्थायी रूप से हटा देगा। इस क्रिया को पूर्ववत नहीं किया जा सकता है।",
        password_confirm: "पुष्टि करने के लिए पासवर्ड दर्ज करें",
        back_up_success: "बैकअप सफलतापूर्वक सिंक किया गया",
        clear_success: "डेटा सफलतापूर्वक साफ़ किया गया",
        backup_none: "कभी नहीं",
        daily: "दैनिक",
        weekly: "साप्ताहिक",
        monthly: "मासिक",
        none: "कोई नहीं",
    },
    Marathi: {
        dashboard: "डॅशबोर्ड",
        expense: "खर्च",
        report: "अहवाल",
        profile: "प्रोफाइल",
        builder_details: "बिल्डर तपशील",
        app_settings: "अॅप सेटिंग्ज",
        logout: "लॉगआउट",
        save_changes: "बदल जतन करा",
        home: "मुख्य",
        account_settings: "खाते सेटिंग्ज",
        app_preferences: "अॅप पसंती",
        personal_info: "वैयक्तिक माहिती",
        confirm_apply: "पुष्टी करा आणि लागू करा",
        hero_title: "तुमचा\nआर्थिक\nसल्लागार",
        hero_subtitle: "बदल घडवून आणणाऱ्या प्रकल्पांमध्ये गुंतवणूक करा. प्रभावशाली उपक्रमांना पाठिंबा देण्यासाठी आणि जगात सकारात्मक बदल घडवण्यासाठी आमच्यात सामील व्हा.",
        get_started: "सुरू करा",
        security: "सुरक्षा",
        security_sublabel: "पासवर्ड आणि प्रमाणीकरण",
        builder_details_sublabel: "व्यवसाय तपशील, GST, PAN आणि पत्ता",
        app_settings_sublabel: "चलन, भाषा, थीम आणि अधिक",
        expense_overview: "खर्च विहंगावलोकन",
        total_expenses: "एकूण खर्च",
        no_expenses: "अद्याप कोणताही खर्च नाही. जोडण्यासाठी + वर टॅप करा.",
        add_expense_title: "खर्च जोडा",
        vendor_name: "विक्रेत्याचे नाव",
        material_category: "साहित्य श्रेणी",
        quantity: "प्रमाण",
        unit: "युनिट",
        rate_per_unit: "प्रति युनिट दर",
        total_amount_label: "एकूण रक्कम",
        payment_mode: "पेमेंट मोड",
        project_tag: "प्रकल्प टॅग",
        notes: "नोट्स",
        add_expense_btn: "खर्च जोडा",
        cancel: "रद्द करा",
        search_placeholder: "विक्रेता किंवा तारीख शोधा...",
        localization: "स्थानिकीकरण",
        default_currency: "डीफॉल्ट चलन",
        app_language: "अॅप भाषा",
        formatting_defaults: "फॉर्मेटिंग आणि डीफॉल्ट",
        date_format: "तारीख स्वरूप",
        default_payment: "डीफॉल्ट पेमेंट मोड",
        appearance: "देखावा",
        theme_mode: "थीम मोड",
        current: "वर्तमान",
        pref_updated: "प्राधान्ये अपडेट केली आणि जागतिक स्तरावर लागू केली!",
        success: "यश",
        error: "त्रुटि",
        fail_save: "प्राधान्ये जतन करण्यात अयशस्वी.",
        select_date: "तारीख निवडा",
        delete: "हटवा",
        confirm_apply_info: "बदलांची पुष्टी केल्यावर ते संपूर्ण अनुप्रयोगात त्वरित लागू होतील.",
        financial_future: "आपल्या आर्थिक भविष्यावर नियंत्रण ठेवा.",
        data_management: "डेटा व्यवस्थापन",
        data_management_sublabel: "बॅकअप, निर्यात आणि सुरक्षित स्टोरेज",
        last_backup: "शेवटचा बॅकअप",
        backup_now: "आता बॅकअप घ्या",
        auto_backup: "ऑटो बॅकअप वारंवारता",
        export_data: "सर्व डेटा निर्यात करा",
        import_data: "एक्सेलमधून आयात करा",
        storage_usage: "स्टोरेज वापर",
        danger_zone: "धोकादायक क्षेत्र",
        clear_all_data: "सर्व डेटा साफ करा",
        confirm_clear_title: "तुम्हाला खात्री आहे का?",
        confirm_clear_msg: "हे तुमचे सर्व खर्च रेकॉर्ड कायमचे हटवेल. ही कृती पूर्ववत केली जाऊ शकत नाही.",
        password_confirm: "पुष्टी करण्यासाठी पासवर्ड टाका",
        back_up_success: "बॅकअप यशस्वीरित्या सिंक झाला",
        clear_success: "डेटा यशस्वीरित्या साफ झाला",
        backup_none: "कधीही नाही",
        daily: "दररोज",
        weekly: "साप्ताहिक",
        monthly: "मासिक",
        none: "काहीही नाही",
    },
    Gujarati: {
        dashboard: "ડેશબોર્ડ",
        expense: "ખર્ચ",
        report: "રિપોર્ટ",
        profile: "પ્રોફાઇલ",
        builder_details: "બિલ્ડર વિગતો",
        app_settings: "એપ્લિકેશન સેટિંગ્સ",
        logout: "લોગઆઉટ",
        save_changes: "ફેરફારો સાચવો",
        home: "હોમ",
        account_settings: "ખાતાની સેટિંગ્સ",
        app_preferences: "એપ્લિકેશન પસંદગીઓ",
        personal_info: "વ્યક્તિગત માહિતી",
        confirm_apply: "પુષ્ટિ કરો અને લાગુ કરો",
        hero_title: "તમારા\nનાણાકીય\nસલાહકાર",
        hero_subtitle: "પરિવર્તન લાવતા પ્રોજેક્ટ્સમાં રોકાણ કરો. પ્રભાવશાળી પહેલને ટેકો આપવા અને વિશ્વમાં સકારાત્મક પરિવર્તન લાવવા માટે અમારી સાથે જોડાઓ.",
        get_started: "શરૂ કરો",
        security: "સુરક્ષા",
        security_sublabel: "પાસવર્ડ અને પ્રમાણીકરણ",
        builder_details_sublabel: "વ્યવસાય વિગતો, GST, PAN અને સરનામું",
        app_settings_sublabel: "ચલણ, ભાષા, થીમ અને વધુ",
        expense_overview: "ખર્ચ વિહંગાવલોકન",
        total_expenses: "કુલ ખર્ચ",
        no_expenses: "હજુ સુધી કોઈ ખર્ચ નથી. ઉમેરવા માટે + ટેપ કરો.",
        add_expense_title: "ખર્ચ ઉમેરો",
        vendor_name: "વિક્રેતાનું નામ",
        material_category: "સામગ્રી કેટેગરી",
        quantity: "જથ્થો",
        unit: "એકમ",
        rate_per_unit: "એકમ દીઠ દર",
        total_amount_label: "કુલ રકમ",
        payment_mode: "ચુકવણી મોડ",
        project_tag: "પ્રોજેક્ટ ટેગ",
        notes: "નોંધો",
        add_expense_btn: "ખર્ચ ઉમેરો",
        cancel: "રદ કરો",
        search_placeholder: "વિક્રેતા અથવા તારીખ શોધો...",
        localization: "સ્થાનિકીકરણ",
        default_currency: "ડિફોલ્ટ ચલણ",
        app_language: "એપ્લિકેશન ભાષા",
        formatting_defaults: "ફોર્મેટિંગ અને ડિફોલ્ટ્સ",
        date_format: "તારીખ ફોર્મેટ",
        default_payment: "ડિફોલ્ટ પેમેન્ટ મોડ",
        appearance: "દેખાવ",
        theme_mode: "થીમ મોડ",
        current: "વર્તમાન",
        pref_updated: "પસંદગીઓ અપડેટ કરવામાં આવી છે અને વૈશ્વિક સ્તરે લાગુ કરવામાં આવી છે!",
        success: "સફળતા",
        error: "ભૂલ",
        fail_save: "પસંદગીઓ સાચવવામાં નિષ્ફળ.",
        select_date: "તારીખ પસંદ કરો",
        delete: "કાઢી નાખો",
        confirm_apply_info: "ફેરફારોની પુષ્ટિ કરવાથી તે સમગ્ર એપ્લિકેશનમાં તરત જ લાગુ થશે.",
        financial_future: "તમારા નાણાકીય ભવિષ્ય પર નિયંત્રણ મેળવો.",
        data_management: "ડેટા મેનેજમેન્ટ",
        data_management_sublabel: "બેકઅપ, નિકાસ અને સુરક્ષિત સ્ટોરેજ",
        last_backup: "છેલ્લું બેકઅપ",
        backup_now: "હવે બેકઅપ લો",
        auto_backup: "ઓટો બેકઅપ ફ્રીક્વન્સી",
        export_data: "બધો ડેટા નિકાસ કરો",
        import_data: "એક્સેલમાંથી આયાત કરો",
        storage_usage: "સ્ટોરેજ વપરાશ",
        danger_zone: "ડેન્જર ઝોન",
        clear_all_data: "બધો ડેટા ભૂંસી નાખો",
        confirm_clear_title: "શું તમે ચોક્કસ છો?",
        confirm_clear_msg: "આ તમારા બધા ખર્ચ રેકોર્ડ્સ કાયમી ધોરણે કાઢી નાખશે. આ ક્રિયા પૂર્વવત્ કરી શકાતી નથી.",
        password_confirm: "પુષ્ટિ કરવા માટે પાસવર્ડ દાખલ કરો",
        back_up_success: "બેકઅપ સફળતાપૂર્વક સમન્વયિત થયું",
        clear_success: "ડેટા સફળતાપૂર્વક ભૂંસી નાખવામાં આવ્યો",
        backup_none: "ક્યારેય નહીં",
        daily: "દૈનિક",
        weekly: "સાપ્તાહિક",
        monthly: "માસિક",
        none: "કોઈ નહીં",
    },
    Tamil: {
        dashboard: "டாஷ்போர்டு",
        expense: "செலவு",
        report: "அறிக்கை",
        profile: "சுயவிவரம்",
        builder_details: "பில்டர் விவரங்கள்",
        app_settings: "ஆப் அமைப்புகள்",
        logout: "வெளியேறு",
        save_changes: "மாற்றங்களைச் சேமி",
        home: "முகப்பு",
        account_settings: "கணக்கு அமைப்புகள்",
        app_preferences: "ஆப் முன்னுரிமைகள்",
        personal_info: "தனிப்பட்ட தகவல்",
        confirm_apply: "உறுதிப்படுத்தி விண்ணப்பிக்கவும்",
        hero_title: "உங்கள்\nநிதி\nவழிகாட்டி",
        hero_subtitle: "மாற்றத்தை ஏற்படுத்தும் திட்டங்களில் முதலீடு செய்யுங்கள். தாக்கத்தை ஏற்படுத்தும் முன்முயற்சிகளை ஆதரிப்பதற்கும் உலகில் நேர்மறையான மாற்றத்தை உருவாக்குவதற்கும் எங்களுடன் சேருங்கள்.",
        get_started: "தொடங்கு",
        security: "பாதுகாப்பு",
        security_sublabel: "கடவுச்சொல் மற்றும் அங்கீகாரம்",
        builder_details_sublabel: "வணிக விவரங்கள், ஜிஎஸ்டி, பான் மற்றும் முகவரி",
        app_settings_sublabel: "நாணயம், மொழி, தீம் மற்றும் பல",
        expense_overview: "செலவு கண்ணோட்டம்",
        total_expenses: "மொத்த செலவுகள்",
        no_expenses: "இன்னும் செலவுகள் எதுவும் இல்லை. சேர்க்க + தட்டவும்.",
        add_expense_title: "செலவைச் சேர்",
        vendor_name: "விற்பனையாளர் பெயர்",
        material_category: "பொருள் வகை",
        quantity: "அளவு",
        unit: "அலகு",
        rate_per_unit: "அலகுக்கான விலை",
        total_amount_label: "மொத்த தொகை",
        payment_mode: "கட்டண முறை",
        project_tag: "திட்டக் குறிச்சொல்",
        notes: "குறிப்புகள்",
        add_expense_btn: "செலவைச் சேர்",
        cancel: "ரத்து செய்",
        search_placeholder: "விற்பனையாளர் அல்லது தேதியைத் தேடுங்கள்...",
        localization: "உள்ளூர்மயமாக்கல்",
        default_currency: "இயல்புநிலை நாணயம்",
        app_language: "ஆப் மொழி",
        formatting_defaults: "வடிவமைப்பு மற்றும் இயல்புநிலைகள்",
        date_format: "தேதி வடிவம்",
        default_payment: "இயல்புநிலை கட்டண முறை",
        appearance: "தோற்றம்",
        theme_mode: "தீம் முறை",
        current: "தற்போதைய",
        pref_updated: "விருப்பத்தேர்வுகள் புதுப்பிக்கப்பட்டு உலகளவில் பயன்படுத்தப்பட்டன!",
        success: "வெற்றி",
        error: "பிழை",
        fail_save: "விருப்பங்களைச் சேமிக்க முடியவில்லை.",
        select_date: "தேதியைத் தேர்ந்தெடு",
        delete: "அழி",
        confirm_apply_info: "மாற்றங்களை உறுதிப்படுத்துவது முழு விண்ணப்பத்திலும் உடனடியாக அவற்றைப் பயன்படுத்தும்.",
        financial_future: "உங்கள் நிதி எதிர்காலத்தை கட்டுப்படுத்துங்கள்.",
        data_management: "தரவு மேலாண்மை",
        data_management_sublabel: "காப்புப்பிரதி, ஏற்றுமதி மற்றும் பாதுகாப்பான சேமிப்பு",
        last_backup: "கடைசி காப்புப்பிரதி",
        backup_now: "இப்போது காப்புப்பிரதி எடுக்கவும்",
        auto_backup: "தானியங்கி காப்புப்பிரதி அதிர்வெண்",
        export_data: "அனைத்து தரவையும் ஏற்றுமதி செய்",
        import_data: "எக்செல் இலிருந்து இறக்குமதி செய்",
        storage_usage: "சேமிப்பக பயன்பாடு",
        danger_zone: "ஆபத்தான பகுதி",
        clear_all_data: "அனைத்து தரவையும் அழி",
        confirm_clear_title: "நிச்சயமாகச் சொல்கிறீர்களா?",
        confirm_clear_msg: "இது உங்கள் அனைத்து செலவு பதிவுகளையும் நிரந்தரமாக அழித்துவிடும். இந்த செயலை மாற்ற முடியாது.",
        password_confirm: "உறுதிப்படுத்த கடவுச்சொல்லை உள்ளிடவும்",
        back_up_success: "காப்புப்பிரதி வெற்றிகரமாக ஒத்திசைக்கப்பட்டது",
        clear_success: "தரவு வெற்றிகரமாக அழிக்கப்பட்டது",
        backup_none: "ஒருபோதும் இல்லை",
        daily: "தினசரி",
        weekly: "வாரம் ஒருமுறை",
        monthly: "மாதம் ஒருமுறை",
        none: "எதுவுமில்லை",
    }
};

export const SettingsProvider = ({ children }) => {
    const [settings, setSettings] = useState({
        currency: "INR",
        language: "English",
        dateFormat: "DD/MM/YYYY",
        defaultPaymentMode: "Cash",
        theme: "dark"
    });

    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadSettings();
    }, []);

    const loadSettings = async () => {
        try {
            const saved = await AsyncStorage.getItem("app_preferences");
            if (saved) {
                setSettings(JSON.parse(saved));
            }
        } catch (e) {
            console.log("Error loading settings:", e);
        } finally {
            setLoading(false);
        }
    };

    const applySettings = async (newSettings) => {
        setSettings(newSettings);
        try {
            await AsyncStorage.setItem("app_preferences", JSON.stringify(newSettings));
        } catch (e) {
            console.log("Error saving settings:", e);
        }
    };

    const t = (key) => {
        return translations[settings.language]?.[key] || translations["English"][key] || key;
    };

    const currencySymbol = settings.currency === "INR" ? "₹" : "$";

    const themeColors = {
        background: settings.theme === "light" ? ["#F8FAFC", "#F1F5F9", "#E2E8F0"] : ["#0F2027", "#203A43", "#2C5364"],
        card: settings.theme === "light" ? "#FFFFFF" : "#1A2B32",
        text: settings.theme === "light" ? "#0F172A" : "#FFFFFF",
        subtext: settings.theme === "light" ? "#64748B" : "rgba(255,255,255,0.5)",
        border: settings.theme === "light" ? "rgba(15, 23, 42, 0.08)" : "rgba(255,255,255,0.05)",
        tabBar: settings.theme === "light" ? "#FFFFFF" : "#0F2027",
        primary: "#4ADE80",
        danger: "#EF4444",
    };

    return (
        <SettingsContext.Provider value={{ settings, applySettings, loading, t, themeColors, currencySymbol }}>
            {children}
        </SettingsContext.Provider>
    );
};

export const useSettings = () => useContext(SettingsContext);
